Para abrir o notebook no Google Colab, altere o domínio `github.com` para `githubtocolab.com`

<div class="alert alert-block alert-danger">
Para praticar programação, é importante que você erre, leia as mensagens de erro e tente corrigí-los.
    
Dessa forma, no Google Colab, é importante que você DESATIVE OS RECURSOS DE AUTOCOMPLETAR:

- Menu Ferramentas -> Configurações
- Na janela que é aberta:
  - Seção Editor -> Desativar "Mostrar sugestões de preenchimento de código com base no contexto"
  - Seção Assistência de IA -> Desabilitar itens

Na versão em inglês:

- Menu Tools -> Settings
- Na janela que é aberta:
  - Seção Editor -> Desativar "Show context-powered code completions"
  - Seção AI Assistance -> Desabilitar itens
</div>

# Introdução ao Python para processamento numérico e análise de dados

# Pandas

O Pandas é uma biblioteca usada para análise de dados em Python.

## 1. Carregando Dados

É possível carregar dados de diversos formatos, por exemplo, o CSV. Os dados são carregados em objetos do tipo DataFrame:

In [3]:
import pandas as pd

df_carregado = pd.read_csv('pessoas.csv')

print("\nPrimeiras 5 linhas do df_carregado:")
df_carregado.head()

Primeiras 5 linhas do df_carregado:

     Nome  Idade          Cidade  Salario
0   Alice     24       São Paulo  5000.00
1     Bob     27  Rio de Janeiro  6500.50
2  Carlos     22  Belo Horizonte  4800.75
3   Diana     32    Porto Alegre  7200.00
4     Eva     29        Curitiba  5800.25

## 2. Seleção de Colunas

Selecionando uma coluna do DataFrame:

In [4]:
### Seleção de uma única coluna (resulta em Series):
coluna_nome = df_carregado['Nome']
print("Tipo da coluna 'Nome':", type(coluna_nome))
print("Primeiras 5 linhas da coluna 'Nome':\n", coluna_nome.head())

Tipo da coluna 'Nome': <class 'pandas.core.series.Series'>
Primeiras 5 linhas da coluna 'Nome':
 0     Alice
1       Bob
2    Carlos
3     Diana
4       Eva
Name: Nome, dtype: object

Também é possível selecionar múltiplas colunas:

In [5]:
### Seleção de múltiplas colunas (resulta em DataFrame):
colunas_nome_idade = df_carregado[['Nome', 'Idade']]
print("Tipo das colunas ['Nome', 'Idade']:", type(colunas_nome_idade))
print("Primeiras 5 linhas das colunas 'Nome' e 'Idade':\n", colunas_nome_idade.head())

Tipo das colunas ['Nome', 'Idade']: <class 'pandas.core.frame.DataFrame'>
Primeiras 5 linhas das colunas 'Nome' e 'Idade':
      Nome  Idade
0   Alice     24
1     Bob     27
2  Carlos     22
3   Diana     32
4     Eva     29

## 3. Criação de Novas Colunas

Criando uma coluna com valores `None`:

In [6]:
df_carregado['Departamento'] = None
df_carregado.columns

Index(['Nome', 'Idade', 'Cidade', 'Salario', 'Departamento'], dtype='object')

In [7]:
df_carregado.head()

     Nome  Idade          Cidade  Salario Departamento
0   Alice     24       São Paulo  5000.00         None
1     Bob     27  Rio de Janeiro  6500.50         None
2  Carlos     22  Belo Horizonte  4800.75         None
3   Diana     32    Porto Alegre  7200.00         None
4     Eva     29        Curitiba  5800.25         None

Criando uma coluna calculada a partir de outra coluna:

In [8]:
df_carregado['Salario_Anual'] = df_carregado['Salario'] * 12

df_carregado.head()

     Nome  Idade          Cidade  Salario Departamento  Salario_Anual
0   Alice     24       São Paulo  5000.00         None        60000.0
1     Bob     27  Rio de Janeiro  6500.50         None        78006.0
2  Carlos     22  Belo Horizonte  4800.75         None        57609.0
3   Diana     32    Porto Alegre  7200.00         None        86400.0
4     Eva     29        Curitiba  5800.25         None        69603.0

## 4. Filtragem de Linhas

Filtrando linhas com base em uma condição:

In [11]:
### Filtragem com uma única condição (Idade > 25):
df_idade_maior_25 = df_carregado.loc[df_carregado['Idade'] > 25]

df_idade_maior_25.head()

    Nome  Idade          Cidade  Salario Departamento  Salario_Anual
1    Bob     27  Rio de Janeiro  6500.50         None        78006.0
3  Diana     32    Porto Alegre  7200.00         None        86400.0
4    Eva     29        Curitiba  5800.25         None        69603.0

Filtrando com base em múltiplas condições:

In [12]:
### Filtragem com múltiplas condições (Cidade == 'São Paulo' E Salario > 5000):
df_multi_condicao = df_carregado.loc[(df_carregado['Cidade'] == 'São Paulo') & (df_carregado['Salario'] >= 5000)]

df_multi_condicao.head()

    Nome  Idade     Cidade  Salario Departamento  Salario_Anual
0  Alice     24  São Paulo   5000.0         None        60000.0

## 5. Seleção de Linhas Específicas

É possível selecionar linhas usando rótulos ou índices:

*   **`loc` (Label-based indexing)**: Seleciona linhas e colunas por seus rótulos (labels) ou um array booleano. Se o índice do DataFrame for numérico e padrão (começando de 0), `loc` pode se comportar de forma semelhante a `iloc` para seleção de linhas por número, mas sua intenção é sempre buscar pelo *rótulo* do índice.
*   **`iloc` (Integer-location based indexing)**: Seleciona linhas e colunas por sua posição inteira. É estritamente baseado na posição numérica (0-indexed) ao longo do eixo, independentemente do rótulo do índice do DataFrame.

Exemplo de seleção com rótulo:

In [13]:
### Seleção de uma linha específica usando .loc (por rótulo/label):
linha_loc_0 = df_carregado.loc[0]

print("Linha com label 0 (usando .loc):\n", linha_loc_0)

Linha com índice 0 (usando .loc):
 Nome                 Alice
Idade                   24
Cidade           São Paulo
Salario             5000.0
Departamento          None
Salario_Anual      60000.0
Name: 0, dtype: object

Exemplo de seleção usando índice:

In [15]:
### Seleção de uma linha específica usando .iloc (por posição inteira/indice):
linha_iloc_0 = df_carregado.iloc[3]

print("Linha na posição 0 (usando .iloc):\n", linha_iloc_0)

Linha na posição 0 (usando .iloc):
 Nome                    Diana
Idade                      32
Cidade           Porto Alegre
Salario                7200.0
Departamento             None
Salario_Anual         86400.0
Name: 3, dtype: object

Observação: Para DataFrames com índices numéricos padrão (0, 1, 2, ...), `.loc[0]` e `.iloc[0]` podem retornar a mesma linha, mas .loc busca pelo rótulo do índice e .iloc pela posição do índice."

## 6. Ordenação de Dados

É possível ordenar os dados de um DataFrame com base nos valores de uma ou mais colunas.

In [16]:
### Ordenação por 'Idade' (crescente):"
df_ordenado_idade = df_carregado.sort_values(by='Idade', ascending=True)
print("Primeiras 5 linhas do DataFrame ordenado por Idade (crescente):\n", df_ordenado_idade.head())

Primeiras 5 linhas do DataFrame ordenado por Idade (crescente):
      Nome  Idade          Cidade  Salario Departamento  Salario_Anual
2  Carlos     22  Belo Horizonte  4800.75         None        57609.0
0   Alice     24       São Paulo  5000.00         None        60000.0
1     Bob     27  Rio de Janeiro  6500.50         None        78006.0
4     Eva     29        Curitiba  5800.25         None        69603.0
3   Diana     32    Porto Alegre  7200.00         None        86400.0

In [17]:
### Ordenação por 'Salario' (decrescente):"
df_ordenado_salario = df_carregado.sort_values(by='Salario', ascending=False)
print("Primeiras 5 linhas do DataFrame ordenado por Salario (decrescente):\n", df_ordenado_salario.head())

Primeiras 5 linhas do DataFrame ordenado por Salario (decrescente):
      Nome  Idade          Cidade  Salario Departamento  Salario_Anual
3   Diana     32    Porto Alegre  7200.00         None        86400.0
1     Bob     27  Rio de Janeiro  6500.50         None        78006.0
4     Eva     29        Curitiba  5800.25         None        69603.0
0   Alice     24       São Paulo  5000.00         None        60000.0
2  Carlos     22  Belo Horizonte  4800.75         None        57609.0

In [18]:
### Ordenação por 'Cidade' (crescente) e 'Idade' (decrescente):"
df_ordenado_multi = df_carregado.sort_values(by=['Cidade', 'Idade'], ascending=[True, False])
print("Primeiras 5 linhas do DataFrame ordenado por Cidade e Idade:", df_ordenado_multi.head())

Primeiras 5 linhas do DataFrame ordenado por Cidade e Idade:      Nome  Idade          Cidade  Salario Departamento  Salario_Anual
2  Carlos     22  Belo Horizonte  4800.75         None        57609.0
4     Eva     29        Curitiba  5800.25         None        69603.0
3   Diana     32    Porto Alegre  7200.00         None        86400.0
1     Bob     27  Rio de Janeiro  6500.50         None        78006.0
0   Alice     24       São Paulo  5000.00         None        60000.0

## 7. Estatísticas Descritivas

É possível obter estatísticas sobre os dados das colunas com os métodos`describe()`, `mean()`, `median()`, `min()`, `max()`, e `value_counts()`.

In [22]:
### Estatísticas descritivas para a coluna 'Salario' (utilizando .describe()):
df_carregado['Salario'].describe()

count       5.000000
mean     5860.300000
std      1008.838494
min      4800.750000
25%      5000.000000
50%      5800.250000
75%      6500.500000
max      7200.000000
Name: Salario, dtype: float64

In [23]:
### Média da coluna 'Idade':
df_carregado['Idade'].mean()

np.float64(26.8)

In [24]:
### Mediana da coluna 'Salario':s
df_carregado['Salario'].median()

5800.25

In [25]:
### Mínimo e Máximo da coluna 'Idade':
min_idade = df_carregado['Idade'].min()
max_idade = df_carregado['Idade'].max()
print(f"Idade Mínima: {min_idade}")
print(f"Idade Máxima: {max_idade}")

Idade Mínima: 22
Idade Máxima: 32

In [28]:
### Contagem de valores únicos para a coluna 'Cidade' (utilizando .value_counts()):"
df3['Cidade'].value_counts()

Cidade
Curitiba          2
Belo Horizonte    1
Porto Alegre      1
Rio de Janeiro    1
São Paulo         1
Name: count, dtype: int64

## 8. Renomear Colunas

É possível renomear colunas com o método `rename()`:

In [29]:
### Renomeando a coluna 'Salario' para 'Renda Mensal':
df_carregado_renomeado = df_carregado.rename(columns={'Salario': 'Renda Mensal'})
print("Primeiras 5 linhas do DataFrame com a coluna renomeada:")
df_carregado_renomeado.head()

Primeiras 5 linhas do DataFrame com a coluna renomeada:

     Nome  Idade          Cidade  Renda Mensal Departamento  Salario_Anual
0   Alice     24       São Paulo       5000.00         None        60000.0
1     Bob     27  Rio de Janeiro       6500.50         None        78006.0
2  Carlos     22  Belo Horizonte       4800.75         None        57609.0
3   Diana     32    Porto Alegre       7200.00         None        86400.0
4     Eva     29        Curitiba       5800.25         None        69603.0

Também é possível renomear mais de uma coluna de uma só vez:

In [31]:
### Renomeando as colunas 'Nome' para 'Primeiro Nome' e 'Cidade' para 'Localidade':
df_carregado_multi_renomeado = df_carregado.rename(columns={'Nome': 'Primeiro Nome', 'Cidade': 'Localidade', 'Salario_Anual': 'Total Comp'})

print("Primeiras 5 linhas do DataFrame com múltiplas colunas renomeadas:")
df_carregado_multi_renomeado.head()

Primeiras 5 linhas do DataFrame com múltiplas colunas renomeadas:

  Primeiro Nome  Idade      Localidade  Salario Departamento  Total Comp
0         Alice     24       São Paulo  5000.00         None     60000.0
1           Bob     27  Rio de Janeiro  6500.50         None     78006.0
2        Carlos     22  Belo Horizonte  4800.75         None     57609.0
3         Diana     32    Porto Alegre  7200.00         None     86400.0
4           Eva     29        Curitiba  5800.25         None     69603.0

## 9. Agregações com Groupby

O `groupby` permite fazer agregações (soma, média, etc.) em grupos de dados.

In [33]:
### Média da Idade por Cidade:
df3.groupby('Cidade')['Idade'].mean()

Cidade
Belo Horizonte    22.0
Curitiba          23.5
Porto Alegre      32.0
Rio de Janeiro    27.0
São Paulo         24.0
Name: Idade, dtype: float64

Também é possível agregar mais de uma coluna por vez, assim como fazer mais de um tipo de agregação (soma e média, por exemplo):

In [34]:
### Soma e Média de Salário e Salário Anual por Cidade:\n"

df_carregado.groupby('Cidade')[['Salario', 'Salario_Anual']].agg(['sum', 'mean'])

                Salario          Salario_Anual
                    sum     mean           sum     mean
Cidade
Belo Horizonte  4800.75  4800.75       57609.0  57609.0
Curitiba        5800.25  5800.25       69603.0  69603.0
Porto Alegre    7200.00  7200.00       86400.0  86400.0
Rio de Janeiro  6500.50  6500.50       78006.0  78006.0
São Paulo       5000.00  5000.00       60000.0  60000.0

## 10. Iteração sobre Linhas

Caso necessário, é possível iterar ao longo das linhas de um DataFrame usando `iterrows()`:

In [35]:
### Iterando sobre as linhas do DataFrame usando iterrows():

for index, row in df_carregado.iterrows():
    print(f"Índice: {index}, Nome: {row['Nome']}, Cidade: {row['Cidade']}")

Índice: 0, Nome: Alice, Cidade: São Paulo
Índice: 1, Nome: Bob, Cidade: Rio de Janeiro
Índice: 2, Nome: Carlos, Cidade: Belo Horizonte
Índice: 3, Nome: Diana, Cidade: Porto Alegre
Índice: 4, Nome: Eva, Cidade: Curitiba

### Vantagens e Desvantagens de `iterrows()`

**Vantagens:**
*   **Acesso fácil a `index` e `row`**: `iterrows()` retorna o índice de cada linha e a linha como uma Series, facilitando o acesso a ambos.
*   **Leitura clara**: Para iterações simples onde o contexto de cada linha é importante, o código pode ser mais legível.

**Desvantagens:**
*   **Lento para DataFrames grandes**: `iterrows()` é significativamente mais lento do que métodos vetorizados, como a criação de colunas calculadas a partir de outras, mostrada anteriormente;
*   **Modificações não seguras**: A documentação do Pandas adverte explicitamente que `iterrows()` não deve ser usado para modificar DataFrames. As modificações em `row` não são refletidas no DataFrame original, e criar um novo DataFrame linha por linha é ineficiente. Para modificações, é preferível usar métodos como `loc` ou `iloc`.

## 11. Salvando DataFrames

É possível salvar dataframes em diversos formatos. Dentre os mais utilizados, estão o CSV e o pickle:

In [37]:
### Salvando DataFrame para CSV:
df_carregado.to_csv('dados_salvos.csv', index=False)
print("DataFrame salvo como 'dados_salvos.csv' com sucesso.")

DataFrame salvo como 'dados_salvos.csv' com sucesso.

In [38]:
### Salvando DataFrame para Pickle:
df_carregado.to_pickle('dados_salvos.pkl')
print("DataFrame salvo como 'dados_salvos.pkl' com sucesso.")

DataFrame salvo como 'dados_salvos.pkl' com sucesso.

## 12. Conversão para Array NumPy

Muitas vezes é necessário converter os dados para o formato NumPy, para utilizar funções externas que esperam esse formato. Para isso, pode-se usar o método `to_numpy()`:

In [39]:
### Conversão do DataFrame para Array NumPy (utilizando .to_numpy()):
np_array_dados = df_carregado.to_numpy()

print("Tipo da variável np_array_dados:", type(np_array_dados))
print("\nConteúdo do Array NumPy:\n", np_array_dados)

Tipo da variável np_array_dados: <class 'numpy.ndarray'>

Conteúdo do Array NumPy:
 [['Alice' 24 'São Paulo' 5000.0 None 60000.0]
 ['Bob' 27 'Rio de Janeiro' 6500.5 None 78006.0]
 ['Carlos' 22 'Belo Horizonte' 4800.75 None 57609.0]
 ['Diana' 32 'Porto Alegre' 7200.0 None 86400.0]
 ['Eva' 29 'Curitiba' 5800.25 None 69603.0]]

Em geral, converte-se apenas dados numéricos:

In [ ]:
df_carregado["Salario"].to_numpy()

## 13. Exercício

Você recebeu um conjunto de dados com transações de clientes em uma corretora no arquivo `dados_clientes.csv`.

- Carregue os dados e visualize as primeiras linhas.

In [41]:
import pandas as pd

df = pd.read_csv('dados_clientes.csv')

df.head()

   Unnamed: 0        Data Cliente  Ativo  Preco  Quantidade    Tipo
0           0  2024-01-05       A  PETR4   30.0         100  Compra
1           1  2024-01-10       B  VALE3   70.0          50  Compra
2           2  2024-01-15       A  PETR4   32.0         150   Venda
3           3  2024-02-01       B  ITUB4   28.0         200  Compra
4           4  2024-02-10       C  VALE3   72.0          80   Venda

- Converta a coluna "Data" para o tipo `datetime`, com

```python
df["Data"] = pd.to_datetime(df["Data"])
```

In [43]:
df["Data"] = pd.to_datetime(df['Data'])

In [45]:
df.dtype["Data"]

AttributeError: 'DataFrame' object has no attribute 'dtype'

- Selecione apenas as colunas: "Cliente", "Ativo" e "Preco".

In [55]:
df_selecao = df[["Cliente", "Ativo", "Preco"]]

df_selecao.head()

  Cliente  Ativo  Preco
0       A  PETR4   30.0
1       B  VALE3   70.0
2       A  PETR4   32.0
3       B  ITUB4   28.0
4       C  VALE3   72.0

- Crie um novo DataFrame contendo apenas as transações do ativo "PETR4".

In [53]:
df_petr4 = df.loc[df["Ativo"] == 'PETR4']

df_petr4.head()

   Unnamed: 0       Data Cliente  Ativo  Preco  Quantidade    Tipo
0           0 2024-01-05       A  PETR4   30.0         100  Compra
2           2 2024-01-15       A  PETR4   32.0         150   Venda

- Crie uma nova coluna chamada `Valor`, e calcule como `Preco * Quantidade`.

In [57]:
df ["Valor"] = df["Preco"] * df["Quantidade"]

df.head()

   Unnamed: 0       Data Cliente  Ativo  Preco  Quantidade    Tipo   Valor
0           0 2024-01-05       A  PETR4   30.0         100  Compra  3000.0
1           1 2024-01-10       B  VALE3   70.0          50  Compra  3500.0
2           2 2024-01-15       A  PETR4   32.0         150   Venda  4800.0
3           3 2024-02-01       B  ITUB4   28.0         200  Compra  5600.0
4           4 2024-02-10       C  VALE3   72.0          80   Venda  5760.0

- Crie uma coluna `Sinal` com os valores `+1` para "Compra" e `-1` para "Venda" usando o método `.map`:

```python
df["Sinal"] = df["Tipo"].map({
    "Compra": 1,
    "Venda": -1
})
```

In [59]:
df["Sinal"] = df["Tipo"].map({
    "Compra": 1,
    "Venda": -1
})

df.head()

,Unnamed: 0,Data,Cliente,Ativo,Preco,Quantidade,Tipo,Valor,Sinal
0,0,2024-01-05,A,PETR4,30.0,100,Compra,3000.0,1
1,1,2024-01-10,B,VALE3,70.0,50,Compra,3500.0,1
2,2,2024-01-15,A,PETR4,32.0,150,Venda,4800.0,-1
3,3,2024-02-01,B,ITUB4,28.0,200,Compra,5600.0,1
4,4,2024-02-10,C,VALE3,72.0,80,Venda,5760.0,-1

- Crie uma nova coluna chamada `Fluxo`, e calcule como `Valor * Sinal`.

- Filtre as transações:
  - Apenas do cliente "A", com "Valor" maior que 3000
  - Filtre apenas as transações de "Venda".

- Use describe() na coluna "Valor".

- Calcule:
  - Valor médio das transações
  - Valor mínimo
  - Valor máximo

- Calcule o valor total negociado por ativo.

- Calcule o fluxo líquido (Fluxo) por cliente.

- Calcule o valor médio das transações por tipo (Compra vs Venda).